// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQCKKYY1dfSAItwJP84rJMLvtkpTyVqUA',
    appId: '1:1050900478191:web:dec01deb983098c282c31a',
    messagingSenderId: '1050900478191',
    projectId: 'ecommerce-ca4dc',
    authDomain: 'ecommerce-ca4dc.firebaseapp.com',
    storageBucket: 'ecommerce-ca4dc.firebasestorage.app',
    measurementId: 'G-RHKVJT1DYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXvs-_J2L5xXqRWFA5xpgktraE_08Dsg',
    appId: '1:1050900478191:android:0e3587deb5df728782c31a',
    messagingSenderId: '1050900478191',
    projectId: 'ecommerce-ca4dc',
    storageBucket: 'ecommerce-ca4dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOAgnV1pTIyDGNA9n3vpFPnPxa8b1RHs',
    appId: '1:1050900478191:ios:0bd3f6d14ffad96982c31a',
    messagingSenderId: '1050900478191',
    projectId: 'ecommerce-ca4dc',
    storageBucket: 'ecommerce-ca4dc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOAgnV1pTIyDGNA9n3vpFPnPxa8b1RHs',
    appId: '1:1050900478191:ios:0bd3f6d14ffad96982c31a',
    messagingSenderId: '1050900478191',
    projectId: 'ecommerce-ca4dc',
    storageBucket: 'ecommerce-ca4dc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQCKKYY1dfSAItwJP84rJMLvtkpTyVqUA',
    appId: '1:1050900478191:web:0eb769881d551fee82c31a',
    messagingSenderId: '1050900478191',
    projectId: 'ecommerce-ca4dc',
    authDomain: 'ecommerce-ca4dc.firebaseapp.com',
    storageBucket: 'ecommerce-ca4dc.firebasestorage.app',
    measurementId: 'G-7EC6TH1P6C',
  );
}
